# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'book',
                'db_table': 'books',
                'verbose_name_plural': 'books',
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('start_page', models.CharField(blank=True, max_length=10, null=True)),
                ('end_page', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contribution_type', models.CharField(choices=[('ES', 'Essay'), ('PO', 'Poetry'), ('LE', 'Letter'), ('BR', 'Book Review'), ('IL', 'Illustration'), ('FI', 'Fiction'), ('AN', 'Announcement'), ('OT', 'Other')], default='ES', max_length=2)),
            ],
            options={
                'verbose_name': 'contribution',
                'db_table': 'contributions',
                'verbose_name_plural': 'contributions',
            },
        ),
        migrations.CreateModel(
            name='ContributionRolePersonContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('contributions', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Contribution')),
            ],
            options={
                'verbose_name': 'Contribution Type',
                'db_table': 'contribution_role_person_contribution',
                'verbose_name_plural': 'Contribution Types',
            },
        ),
        migrations.CreateModel(
            name='Correspondence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'correspondence',
                'db_table': 'correspondence',
                'verbose_name_plural': 'correspondence',
            },
        ),
        migrations.CreateModel(
            name='CreatorBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_role', models.CharField(choices=[('AU', 'Author'), ('TR', 'Translator'), ('Ar', 'Artist'), ('PR', 'Prologuist')], default='AU', max_length=2)),
                ('notes', models.TextField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.Book')),
            ],
        ),
        migrations.CreateModel(
            name='CreatorContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_role', models.CharField(choices=[('AU', 'Author'), ('TR', 'Translator'), ('AR', 'Artist')], default='AU', max_length=2)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.Contribution')),
            ],
        ),
        migrations.CreateModel(
            name='DescriptiveBibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.TextField(blank=True, null=True)),
                ('binding', models.TextField(blank=True, null=True)),
                ('typography', models.TextField(blank=True, null=True)),
                ('colophon', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'descriptive bibliography',
                'db_table': 'descriptive_bibliography',
                'verbose_name_plural': 'descriptive bibliographies',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'event',
                'db_table': 'events',
                'verbose_name_plural': 'events',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('printer', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('descriptive_bibliography', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.DescriptiveBibliography')),
            ],
            options={
                'verbose_name': 'issue',
                'db_table': 'issues',
                'verbose_name_plural': 'issues',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('occupation_type', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'occupation',
                'db_table': 'occupations',
                'verbose_name_plural': 'occupations',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('deathdate', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('viaf_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'people',
                'db_table': 'people',
                'verbose_name_plural': 'people',
            },
        ),
        migrations.CreateModel(
            name='Periodicals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=15, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'periodical',
                'db_table': 'periodicals',
                'verbose_name_plural': 'periodicals',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'place',
                'db_table': 'places',
                'verbose_name_plural': 'places',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Place')),
            ],
            options={
                'verbose_name': 'repository',
                'db_table': 'repository',
                'verbose_name_plural': 'repositories',
            },
        ),
        migrations.AddField(
            model_name='people',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_born', to='people.Place'),
        ),
        migrations.AddField(
            model_name='people',
            name='deathplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='people_died', to='people.Place'),
        ),
        migrations.AddField(
            model_name='people',
            name='occupations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Occupation'),
        ),
        migrations.AddField(
            model_name='issue',
            name='periodicals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Periodicals'),
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Place'),
        ),
        migrations.AddField(
            model_name='descriptivebibliography',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Repository'),
        ),
        migrations.AddField(
            model_name='creatorcontribution',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.People'),
        ),
        migrations.AddField(
            model_name='creatorbook',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='people.People'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='descriptive_bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.DescriptiveBibliography'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='location_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correspondence_received_at', to='people.Place'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='location_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correspondence_sent_to', to='people.Place'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correspondence_received', to='people.People'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='correspondence_sent', to='people.People'),
        ),
        migrations.AddField(
            model_name='contributionrolepersoncontribution',
            name='creator_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.CreatorContribution'),
        ),
        migrations.AddField(
            model_name='contributionrolepersoncontribution',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.People'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Issue'),
        ),
        migrations.AddField(
            model_name='book',
            name='descriptive_bibliography',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.DescriptiveBibliography'),
        ),
        migrations.AddField(
            model_name='book',
            name='occupations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Occupation'),
        ),
        migrations.AddField(
            model_name='book',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.People'),
        ),
    ]
