# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_updates_to_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionrolepersoncontribution',
            name='contributions',
        ),
        migrations.RemoveField(
            model_name='contributionrolepersoncontribution',
            name='creator_role',
        ),
        migrations.RemoveField(
            model_name='contributionrolepersoncontribution',
            name='people',
        ),
        migrations.DeleteModel(
            name='ContributionRolePersonContribution',
        ),
    ]
