# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_post_managed_revisions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descriptivebibliography',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='book',
            name='descriptive_bibliography',
        ),
        migrations.RemoveField(
            model_name='correspondence',
            name='descriptive_bibliography',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='descriptive_bibliography',
        ),
        migrations.AddField(
            model_name='book',
            name='binding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='colophon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='paper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Repository'),
        ),
        migrations.AddField(
            model_name='book',
            name='typography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='paper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Repository'),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='binding',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='colophon',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='paper',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Repository'),
        ),
        migrations.AddField(
            model_name='issue',
            name='typography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DescriptiveBibliography',
        ),
    ]
