# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-21 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_updated_data_in_occupations_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occupation',
            old_name='occupation_role',
            new_name='occupation_type',
        ),
    ]
