# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-26 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_changed_occupations_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='occupation_type',
            field=models.CharField(choices=[('WR', 'Writer'), ('PR', 'Producer'), ('AR', 'Artist'), ('AT', 'Activist'), ('AC', 'Academic'), ('SO', 'Socialite')], default='WR', max_length=2),
        ),
    ]
