# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_updated_charfield_in_occupations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='binding',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='typography',
        ),
        migrations.AddField(
            model_name='issue',
            name='arrow_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='cover_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
