# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0011_updated_CharField_in_issues'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('name',), 'verbose_name': 'place', 'verbose_name_plural': 'places'},
        ),
        migrations.RemoveField(
            model_name='people',
            name='occupations',
        ),
        migrations.AddField(
            model_name='people',
            name='occupations',
            field=models.ManyToManyField(blank=True, to='people.Occupation'),
        ),
    ]
