# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_updated_contribution_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='repository',
        ),
        migrations.AddField(
            model_name='periodicals',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='people.Repository'),
        ),
    ]
