# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_auto_20180402_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='viaf_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
