# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-02 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20180402_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='binding',
        ),
        migrations.RemoveField(
            model_name='book',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='book',
            name='typography',
        ),
    ]
