# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-03 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20180402_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='repository',
        ),
        migrations.AddField(
            model_name='book',
            name='printer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
