# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20180403_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondence',
            old_name='date',
            new_name='date_on_envelope',
        ),
        migrations.AddField(
            model_name='correspondence',
            name='date_on_letter',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='mentions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correspondence',
            name='pages',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
