# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0019_auto_20180404_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='occupations',
        ),
        migrations.AlterField(
            model_name='book',
            name='people',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.People'),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Issue'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='location_received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_received_at', to='people.Place'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='location_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_sent_to', to='people.Place'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_received', to='people.People'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Repository'),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correspondence_sent', to='people.People'),
        ),
        migrations.AlterField(
            model_name='creatorbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Book'),
        ),
        migrations.AlterField(
            model_name='creatorbook',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.People'),
        ),
        migrations.AlterField(
            model_name='creatorcontribution',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Contribution'),
        ),
        migrations.AlterField(
            model_name='creatorcontribution',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.People'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Place'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='periodicals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Periodicals'),
        ),
        migrations.AlterField(
            model_name='people',
            name='birthplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_born', to='people.Place'),
        ),
        migrations.AlterField(
            model_name='people',
            name='deathplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people_died', to='people.Place'),
        ),
        migrations.AlterField(
            model_name='periodicals',
            name='repository',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Repository'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Place'),
        ),
    ]
